
-- countries
INSERT INTO maa VALUES ('Afganistan');
INSERT INTO maa VALUES ('Alankomaat');
INSERT INTO maa VALUES ('Albania');
INSERT INTO maa VALUES ('Algeria');
INSERT INTO maa VALUES ('Angola');
INSERT INTO maa VALUES ('Andorra');
INSERT INTO maa VALUES ('Arabiemiirikunnat');
INSERT INTO maa VALUES ('Argentiina');
INSERT INTO maa VALUES ('Armenia');
INSERT INTO maa VALUES ('Australia');
INSERT INTO maa VALUES ('Azerbaidzan');
INSERT INTO maa VALUES ('Bangladesh');
INSERT INTO maa VALUES ('Belgia');
INSERT INTO maa VALUES ('Benin');
INSERT INTO maa VALUES ('Bhutan');
INSERT INTO maa VALUES ('Belize');
INSERT INTO maa VALUES ('Bolivia');
INSERT INTO maa VALUES ('Bosnia-Hertsegovina');
INSERT INTO maa VALUES ('Botswana');
INSERT INTO maa VALUES ('Brunei');
INSERT INTO maa VALUES ('Bulgaria');
INSERT INTO maa VALUES ('Brasilia');
INSERT INTO maa VALUES ('Burkina Faso');
INSERT INTO maa VALUES ('Chad');
INSERT INTO maa VALUES ('Chile');
INSERT INTO maa VALUES ('Dominikaaninen tasavalta');
INSERT INTO maa VALUES ('Ecuador');
INSERT INTO maa VALUES ('Egypti');
INSERT INTO maa VALUES ('El Salvador');
INSERT INTO maa VALUES ('Eritrea');
INSERT INTO maa VALUES ('Espanja');
INSERT INTO maa VALUES ('Etelä-Afrikka');
INSERT INTO maa VALUES ('Etelä-Korea');
INSERT INTO maa VALUES ('Etelä-Sudan');
INSERT INTO maa VALUES ('Etiopia');
INSERT INTO maa VALUES ('Filippiinit');
INSERT INTO maa VALUES ('Georgia');
INSERT INTO maa VALUES ('Ghana');
INSERT INTO maa VALUES ('Haiti');
INSERT INTO maa VALUES ('Irak');
INSERT INTO maa VALUES ('Iran');
INSERT INTO maa VALUES ('Irlanti');
INSERT INTO maa VALUES ('Islanti');
INSERT INTO maa VALUES ('Italia');
INSERT INTO maa VALUES ('Itävalta');
INSERT INTO maa VALUES ('Indonesia');
INSERT INTO maa VALUES ('Intia');
INSERT INTO maa VALUES ('Japani');
INSERT INTO maa VALUES ('Jamaika');
INSERT INTO maa VALUES ('Jemen');
INSERT INTO maa VALUES ('Kambodia');
INSERT INTO maa VALUES ('Kamerun');
INSERT INTO maa VALUES ('Kanada');
INSERT INTO maa VALUES ('Kazakhstan');
INSERT INTO maa VALUES ('Kenia');
INSERT INTO maa VALUES ('Keski-Afrikan Tasavalta');
INSERT INTO maa VALUES ('Kiina');
INSERT INTO maa VALUES ('Kirgisia');
INSERT INTO maa VALUES ('Kreikka');
INSERT INTO maa VALUES ('Kolumbia');
INSERT INTO maa VALUES ('Kongo');
INSERT INTO maa VALUES ('Kongon demokraattinen tasavalta');
INSERT INTO maa VALUES ('Kuuba');
INSERT INTO maa VALUES ('Kuwait');
INSERT INTO maa VALUES ('Laos');
INSERT INTO maa VALUES ('Latvia');
INSERT INTO maa VALUES ('Lesotho');
INSERT INTO maa VALUES ('Libanon');
INSERT INTO maa VALUES ('Liberia');
INSERT INTO maa VALUES ('Libya');
INSERT INTO maa VALUES ('Liettua');
INSERT INTO maa VALUES ('Luxembourg');
INSERT INTO maa VALUES ('Madagaskar');
INSERT INTO maa VALUES ('Malesia');
INSERT INTO maa VALUES ('Marokko');
INSERT INTO maa VALUES ('Mauritania');
INSERT INTO maa VALUES ('Meksiko');
INSERT INTO maa VALUES ('Mongolia');
INSERT INTO maa VALUES ('Myanmar');
INSERT INTO maa VALUES ('Namibia');
INSERT INTO maa VALUES ('Nepal');
INSERT INTO maa VALUES ('Nigaraqua');
INSERT INTO maa VALUES ('Niger');
INSERT INTO maa VALUES ('Nigeria');
INSERT INTO maa VALUES ('Norja');
INSERT INTO maa VALUES ('Norsunluurannikko');
INSERT INTO maa VALUES ('Oman');
INSERT INTO maa VALUES ('Pakistan');
INSERT INTO maa VALUES ('Panama');
INSERT INTO maa VALUES ('Papua Uusi-Guinea');
INSERT INTO maa VALUES ('Paraguay');
INSERT INTO maa VALUES ('Peru');
INSERT INTO maa VALUES ('Puola');
INSERT INTO maa VALUES ('Pohjois-Korea');
INSERT INTO maa VALUES ('Portugali');
INSERT INTO maa VALUES ('Ranska');
INSERT INTO maa VALUES ('Romania');
INSERT INTO maa VALUES ('Ruanda');
INSERT INTO maa VALUES ('Ruotsi');
INSERT INTO maa VALUES ('Saudi-Arabia');
INSERT INTO maa VALUES ('Saksa');
INSERT INTO maa VALUES ('Sambia');
INSERT INTO maa VALUES ('San Marino');
INSERT INTO maa VALUES ('Senegal');
INSERT INTO maa VALUES ('Serbia');
INSERT INTO maa VALUES ('Singapore');
INSERT INTO maa VALUES ('Slovakia');
INSERT INTO maa VALUES ('Slovenia');
INSERT INTO maa VALUES ('Somalia');
INSERT INTO maa VALUES ('Suomi');
INSERT INTO maa VALUES ('Suriname');
INSERT INTO maa VALUES ('Sveitsi');
INSERT INTO maa VALUES ('Syyria');
INSERT INTO maa VALUES ('Tadzikistan');
INSERT INTO maa VALUES ('Taiwan');
INSERT INTO maa VALUES ('Tanska');
INSERT INTO maa VALUES ('Tansania');
INSERT INTO maa VALUES ('Thaimaa');
INSERT INTO maa VALUES ('Togo');
INSERT INTO maa VALUES ('Tsekki');
INSERT INTO maa VALUES ('Turkki');
INSERT INTO maa VALUES ('Turkmenistan');
INSERT INTO maa VALUES ('Uganda');
INSERT INTO maa VALUES ('Ukraina');
INSERT INTO maa VALUES ('Unkari');
INSERT INTO maa VALUES ('Uruguay');
INSERT INTO maa VALUES ('Uusi-Seelanti');
INSERT INTO maa VALUES ('Uzbekistan');
INSERT INTO maa VALUES ('Valko-Venäjä');
INSERT INTO maa VALUES ('Venezuela');
INSERT INTO maa VALUES ('Venäjä');
INSERT INTO maa VALUES ('Vietnam');
INSERT INTO maa VALUES ('Viro');
INSERT INTO maa VALUES ('Yhdistynyt Kuningaskunta');
INSERT INTO maa VALUES ('Yhdysvallat');
INSERT INTO maa VALUES ('Zimbabwe');








-- persons
INSERT INTO henkilo VALUES(1,'Erkki','Esimerkkinen','012345678','erkki.esimerkkinen@gmail.com',FALSE,TRUE,'2006-04-12 12:00:00',NULL);
INSERT INTO henkilo VALUES(2,'Ulla','Esimerkkinen','02348596','ulla.esimerkkinen@gmail.com',FALSE,TRUE,'2006-04-10 14:00:00',NULL);
INSERT INTO henkilo VALUES(3,'Akseli','Ollila','09485067','akseli.ollila@gmail.com',FALSE,TRUE,'2008-07-18 18:00:00',NULL);
INSERT INTO henkilo VALUES(4,'Omistaja','Neilikka','08590649','kauppias.kauppila@gmail.com',TRUE,TRUE,'2005-07-27 07:00:00',NULL);
INSERT INTO henkilo VALUES(5,'Työntekijä','Neilikka','09580694','tyontekija.neilikka@gmail.com',TRUE,TRUE,'2005-07-31 07:00:00',NULL);
-- addresses
INSERT INTO osoite VALUES(1,'Esimerkkikatu 8 E','08596784','84958','Keuruu','Keski-Suomi',NULL,'Suomi');
INSERT INTO osoite VALUES(3,'Ollilakuja 8 H','09485904','38495','Savonlinna','Etelä-Savo',NULL,'Suomi');
INSERT INTO osoite VALUES(4,'Neilikkakatu 31 E','048590766','30495','Vantaa','Uusimaa',NULL,'Suomi');
INSERT INTO osoite VALUES(5,'Neilikkakatu 31 E','048590766','30495','Vantaa','Uusimaa',NULL,'Suomi');